### ISSUE TITLE
Incorrect class key in services

### ISSUE THREAD

**Issue by curtisghanson** [willdurand/BazingaFakerBundle#48]
The following file: https://github.com/willdurand/BazingaFakerBundle/blob/master/Resources/config/services.xml

Line 29.

Reads:

```xml
        <service id="Bazinga\Bundle\FakerBundle\Command\PopulateCommand" class="%faker.populate.class%">
            <tag name="console.command" />
        </service>
```

But should read:
```xml
        <service id="Bazinga\Bundle\FakerBundle\Command\PopulateCommand" class="%faker.populate_command.class%">
            <tag name="console.command" />
        </service>
```

This causes `composer require willdurand/faker-bundle:dev-master` to fail when installing for Symfony 4.

**Comment by alister** [comment]
Here are another view of the two lines in FakerBundle/Resources/config/services.xml, lines 10 & 29, lightly edited for the parameter ordering. You see the key & class on each line should be referring to the same thing.
```
<parameter key="faker.populate_command.class">Bazinga\Bundle\FakerBundle\Command\PopulateComman</parameter>
<service class="%faker.populate.class%" id="Bazinga\Bundle\FakerBundle\Command\PopulateComman">
```
